version: '3.9'

services:
  {ContainerName}-dev:
    image: ${DOCKER_REGISTRY-}{ContainerName}
    build:
      context: .
      dockerfile: ./Dockerfile-dev
  {ContainerName}-test:
    image: ${DOCKER_REGISTRY-}{ContainerName}
    build:
      context: .
      dockerfile: ./Dockerfile-test
  {ContainerName}-prod:
    image: ${DOCKER_REGISTRY-}{ContainerName}
    build:
      context: .
      dockerfile: ./Dockerfile
